config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'
  resources :users, only: [:new, :create]
  resources :sessions, only: [:new, :create, :destroy]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  private
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_url, notice: "Logged in!"
    else
      flash.now[:alert] = "Invalid email or password"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "Logged out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
      if @user.save
        redirect_to root_url, notice: "Welcome"
      else
        render 'new'
      end
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
    render 'index'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AngeLopez</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'style.scss' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if flash[:notice] %>
      <p id="notice"><%= flash[:notice] %></p>
    <% end %>
    <% if flash[:alert] %>
      <p id="alert"><%= flash[:alert] %></p>
    <% end %>

    <%= yield %>

    <p class="userinfo">
      <% if current_user %>
        Signed in as <%= current_user.name %>. <%= link_to "Log out", session_path("current"), :method => :delete %>
      <% else %>
        <%= link_to "Log in", new_session_path %> or <%= link_to "Sign up", new_user_path %>
      <% end %>
    </p>
  </body>
</html>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :name %><br/>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br/>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br/>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br/>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions"><%= f.submit %></div>
<% end %>

app/views/welcome/index.html.erb
<body>
  <header>
    <div class="background_image">

      <!-- <img src="<%= image_path('angelcannes.jpg') %>" alt="Cannes" /> -->
      <span class="info">
        <h1>AngeLopez</h1>
        <p>Full Stack Web Developer, B.Comm - Business Technology Management Candidate (June 2017), Baker/Cake Decorator</p>

        <a class="icon" href="https://github.com/theAngeLopez"><img src=<%=image_path('github42.png')%> alt="Github"> </a>
        <a class="icon" href="https://twitter.com/theAngeLopez"><img src=<%=image_path('twitter42.png')%> alt="Twitter"> </a>
        <a class="icon" href="http://angelcake.co"><img src=<%=image_path('angelcake100.png')%> alt="AngelCAKE"> </a>
        <a class="icon" href="https://ca.linkedin.com/in/theangelopez"><img src=<%=image_path('linkedin42.png')%> alt="LinkedIn"> </a>
        <a class="icon" href="http://angelcake.co"><img src=<%=image_path('email100.png')%> alt="email"> </a>
      </span>
    </div>
  </header>

  <main>
    <h2>About</h2>

    <p>I am a motivated final-year business technology management student with interests in technology, baking, public speaking, music, and DIY through various mediums (like coding and cakes!).
I am a firm believer in doing what you love so discovering or creating ways to make my interests not only effective, but also profitable are my main goals.</p>


    <div id="portfolio">
    <h2>Projects</h2>

    <h3>Ripple</h3>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Modi, earum ex consequuntur facilis adipisci vero alias sit quidem doloremque hic quam suscipit, illum quibusdam saepe molestias neque, velit. Obcaecati, quidem.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Suscipit voluptas officiis assumenda exercitationem saepe quas. Veniam perferendis quae nobis. Labore quaerat, culpa et velit id eum ipsam. Dolor aspernatur, earum.</p>
    <a href="http://rippleripple.herokuapp.com/"></a>

    <h3>Rainforest</h3>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ipsum ad voluptatem, dolorum minus impedit quidem nam necessitatibus aperiam officia debitis dolorem quaerat, praesentium incidunt, eos sunt laudantium quod dolore delectus!Lorem ipsum dolor sit amet, consectetur adipisicing elit. Exercitationem repellat eveniet architecto quidem ipsam et quas vel. Id eaque atque dolorem, architecto? Quibusdam in eius nisi voluptatibus esse asperiores. Ex!</p>
    </div>
  </main>
  <footer>

  </footer>
</body>